### ISSUE TITLE
Helm values.schema.json and failedTemplate errorMessage

### ISSUE THREAD

**Issue by davidholsgrove** [quintush/helm-unittest#134] opened 2021-10-19 16:05 UTC
Hi @quintush, first off - thanks for the continued work on helm-unittest, its fantastic!

I've been adding a `values.schema.json` to validate the inputs to the chart that I'm also testing.

I've got a simple validation on my `.Values.deployment.replicas` that its a required field, and must be of type integer, e.g;

```json
    "deployment": {
      "type": "object",
      "required": [
        "replicas"
      ],
      "properties": {
        "replicas": {
          "type": "integer"
        },
```

which gives the right validation on use of helm cli;

```bash
$ helm lint example --set deployment.replicas="'2'"

==> Linting example
[INFO] Chart.yaml: icon is recommended
[ERROR] values.yaml: - deployment.replicas: Invalid type. Expected: integer, given: string

[ERROR] templates/: values don't meet the specifications of the schema(s) in the following chart(s):
example:
- deployment.replicas: Invalid type. Expected: integer, given: string


Error: 1 chart(s) linted, 1 chart(s) failed
```

```bash
$ helm lint example --set deployment.replicas=2
==> Linting example
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

I've got a helm-unittest case which tries to pass in replicas as a string (and also null). I attempted a few combinations of the multiline string for the errorMessage, but I'm not sure its being captured as this is thrown by helm validation not template rendering I guess?

```yaml
  - it: should throw linting error if the number of initial replicas is passed as string
    set:
      deployment:
        replicas: "6"
    asserts:
      - failedTemplate:
          errorMessage: |
            Error: values don't meet the specifications of the schema(s) in the following chart(s):
            example:
            - deployment.replicas: Invalid type. Expected: integer, given: string
```

result looks like;

```bash
$ helm unittest -f tests/deployment_test.yaml example --helm3

### Chart [ example ] example

 FAIL  test deployment	example/tests/deployment_test.yaml
	- should throw linting error if the number of initial replicas is passed as string
		Error: values don't meet the specifications of the schema(s) in the following chart(s):
example:
- deployment.replicas: Invalid type. Expected: integer, given: string
```

Any ideas if this is possible to test?

**Comment by faithdoub** [comment] 2022-02-17 10:40
Want to reiterate what @davidholsgrove said.  Appreciate this plug in @quintush 

I am also experiencing this issue and it's an important use case for me.

**Comment by rquinio1A** [comment] 2022-02-17 11:32
Maybe it's the same root cause as #144 (fixed in master, not yet released) ?
Because looking at the code, schema is suposed to be validated here https://github.com/quintush/helm-unittest/blob/master/pkg/unittest/test_job.go#L443 (relying on https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/chartutil/values.go#L159). 
I guess a test with a JSON schema, should be added to https://github.com/quintush/helm-unittest/tree/master/test/data/v3

**Closed** 2022-09-24 13:23 UTC
